### ISSUE TITLE
overwriting custom $primary color

### ISSUE THREAD

**Issue by nothingismagick** [hawkeye64/q-colorize-mixin#1]
So, trying to figure out what is going wrong (related to this issue):
https://github.com/quasarframework/quasar-ui-qcalendar/issues/57

If I remove these lines:

https://github.com/hawkeye64/q-colorize-mixin/blob/dae39d5e9268b48260096d834cbcd50d9e9e6cfb/ui/src/components/QColorizeMixin.sass#L3-L11

Then my $primary color does not get overwritten (outside of the calendar component). The calendar, however, stays at the default quasar $primary color.

**Comment by hawkeye64** [comment]
Thanks for researching and reporting. :heart:
Fix will be in v1.0.1

**Comment by nothingismagick** [comment]
`QColorizeMixin.sass`

So, If i change my color here, ie: `$colors: ('primary': #c0ffee, ...`
then it DOES modify my $primary color - so this approach is the real culprit.
